services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gtc-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_SA_PASSWORD}
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -N -Q 'SELECT 1' -b -o /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s

  web:
    build:
      context: .
      dockerfile: src/GestionTicketsCombustible.Web/Dockerfile
    container_name: gtc-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=GestionTicketsCombustibleDb;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;"
      TicketSeguridad__ClaveFirma: ${TICKET_CLAVE_FIRMA}
      Aplicacion__UrlBase: "http://localhost:5122"
      Smtp__RemitenteCorreo: ${SMTP_CORREO}
      Smtp__Usuario: ${SMTP_CORREO}
      Smtp__Password: ${SMTP_PASSWORD}
      AdminInicial__UserName: ${ADMIN_USERNAME}
      AdminInicial__Email: ${ADMIN_EMAIL}
      AdminInicial__NombreCompleto: ${ADMIN_NOMBRE}
      AdminInicial__Password: ${ADMIN_PASSWORD}
    ports:
      - "5122:8080"

  api:
    build:
      context: .
      dockerfile: src/GestionTicketsCombustible.Api/Dockerfile
    container_name: gtc-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=GestionTicketsCombustibleDb;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;"
      TicketSeguridad__ClaveFirma: ${TICKET_CLAVE_FIRMA}
      Jwt__ClaveSecreta: ${JWT_CLAVE_SECRETA}
    ports:
      - "7262:8080"

  pwa:
    build:
      context: src/GestionTicketsCombustible.Pwa
      dockerfile: Dockerfile
    container_name: gtc-pwa
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"
    ports:
      - "5199:8080"
    depends_on:
      - api

volumes:
  sqlserver_data: